### ISSUE TITLE
PR into main repository?

### ISSUE THREAD

**Issue by ullmark** [lstyles/HashidsNetCore#1]
Hi, 
I generally fine with you copying my code and releasing it as a new package, but for the communities sake, maybe you could have forked and sent me a pull request instead? It's not that the main repository for hashids.net is abandoned, it's just that .net core have been in alpha then and release candidate for a long while with a changing api. I also work with much other than .NET so I've not had time to learn dotnetcore yet. 

You wouldn't want to collaborate into creating a new version of Hashids instead? I've already started converting it to a "portable library" (which seem a good fit) in a branch but haven't gotten the unit tests to run correctly yet in that new project type. There is also important of releasing a new version that doesn't break any older projects.

Feel free to close this issue if you don't feel like collaborating with this 😉 
Have a nice day!

**Comment by lstyles** [comment]
@ullmark Apologies for the late reply. I've just noticed this now.

The reason I created this package is because there was unmerged pull on your repo, that would solve my issue (so I thought). That pull sat there since march I believe, which lead me to believe that the project was no longer being maintained.

I then decided to clone the repo of the author of the PR and use that instead. Unfortunately, this is when I struggled to get tests working because of it being a portable library. There is some dependency conflict between the test suite used and xunit.

This is when I decided to make it into a package. I'd be more than happy to collaborate, or straight up make this repo yours but I don't believe "portable library" is a good choice. Hasn't it been abandoned by Microsoft in favour of .NET Standard?

Thanks for getting in touch and thanks for the work you've put in maintaining Hashids for .NET.

Edit:
Take a look at this:

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

By the way, I hope it's clear from the project readme that I wasn't trying to maliciously take credit for your work.

**Comment by lstyles** [comment]
@ullmark Take a look at this:

https://docs.microsoft.com/en-us/dotnet/articles/standard/library

By the way, I hope it's clear from the project readme that I wasn't trying to maliciously take credit for your work.

**Comment by ullmark** [comment]
@lstyles Hey! no worries at all and don't worry about me thinking that you are taking credits, after all I only ported the library in the first place 😄 

I feel a little bad for not merging said PR, but to be honest, didn't really know how to validate if it was a good idea, and I haven't been working much with windows/.net at all lately. The good thing is that I just started working in .NET again, so I have everything I need again. 

Hmm, when I heard about "portable library" I was hopeful, after all this is just one class... seems very portable 😏 Maybe it's best to use build directives and multiple projects then... And include the  class file in each project. Similar to the setup (same principle) used here https://github.com/JeremySkinner/FluentValidation/tree/master/src (a library I tend to use whenever I want to Validate stuff).

Closing this, but I'll open up a PR in my repo soon, maybe we can discuss there... I've been looking for someone to help out with the lib, since people seem to be using it, and I don't always have the time or even windows installed, hehe.
